Homework 2
================
Siyan Wen
2023-09-27

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
```

## Problem 1

First, clean the data in pols-month.csv.

``` r
pols_month_df= read_csv("data/pols-month.csv")|> 
  janitor::clean_names()|>
  separate(mon,into=c("year", "month","day"),sep='-') |>     #separate by"-"
  mutate(month = month.abb[as.numeric(month)]) |>     #replace month with name
  mutate(
    prez_dem=case_match(prez_dem,
      1 ~ "dem",
      0 ~ "gop"
        ))|>
  rename(president=prez_dem)|>
  select(year,month,president,gov_gop,sen_gop,rep_gop,gov_dem,sen_dem,rep_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Second, clean the data in snp.csv.

``` r
snp_df= read_csv("data/snp.csv")|>
  janitor::clean_names()|>
  separate(date,into=c("month", "day","year"),sep='/')|>
  mutate(month = month.abb[as.numeric(month)])|>
  select(year, month, close) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Third, clean the data in unemplyment.csv.

``` r
unemployment_df=read_csv("data/unemployment.csv")|>
  rename(year=Year)|>
   pivot_longer(
    Jan:Dec, 
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(year=as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Finally, merge three datasets.

``` r
merge_df = 
  left_join(pols_month_df, snp_df)
```

    ## Joining with `by = join_by(year, month)`

``` r
merge_final_df=
  left_join(merge_df, unemployment_df)
```

    ## Joining with `by = join_by(year, month)`

## Problem 2

Read and clean the Mr. Trash Wheel sheet:

``` r
mr.trashwheel_df=
  readxl::read_excel("data/trash_wheel.xlsx",sheet = 1, range ="A2:N586")|>
  janitor::clean_names()|>
  mutate(homes_powered=(weight_tons*500)/30)|>
  mutate(trash_wheel_name="Mr.Trash Wheel")

mr.trashwheel_df$year = as.numeric(as.character(mr.trashwheel_df$year))
```

Read and clean the Professor Trash Wheel sheet:

``` r
professor.trashwheel_df=
  readxl::read_excel("data/trash_wheel.xlsx",sheet = 2 , range ="A2:M108")|>
  janitor::clean_names()|>
  mutate(homes_powered=(weight_tons*500)/30)|>
  mutate(trash_wheel_name="Professor Trash Wheel")
```

Read and clean the Gwynnda Trash Wheel sheet:

``` r
gwynnda.trashwheel_df=
  readxl::read_excel("data/trash_wheel.xlsx",sheet = 4, range ="A2:L157")|>
  janitor::clean_names()|>
  mutate(homes_powered=(weight_tons*500)/30)|>
  mutate(trash_wheel_name="Gwynnda Trash Wheel")
```

Combine three datasets and clean:

``` r
trashwheel_df=
  bind_rows(mr.trashwheel_df,professor.trashwheel_df,gwynnda.trashwheel_df)|>
  janitor::clean_names()|>
  relocate(homes_powered,.before = plastic_bottles)|>
  relocate(trash_wheel_name)

trashwheel_df[is.na(trashwheel_df)] <- 0
```

**Discussion:** In total, the resulting dataset contains `845`
observations. The number of the total observation is the sum of number
of the observation in the all three datasets `(845=155+584+106)`.

Additional, the resulting dataset contains `15` variables such as the
trash wheel name, the dumpster number, date, the weight of trash, the
homes powered estimation and so on. From the dataset, we can tell that:
in 2017/01/02, Professor Trash Wheel’s dumpster number 1 has collected
`1.79` tons of trash, and these trash can be convert into electricity
that can be used to support `29.83` household.

``` r
sum(professor.trashwheel_df$weight_tons)
```

    ## [1] 216.26

``` r
sum(filter(gwynnda.trashwheel_df,month=='July',year==2021)$cigarette_butts)
```

    ## [1] 16300

For available data, the total weight of trash collected by Professor
Trash Wheel was 216.26 tons. The total number of cigarette butts
collected by Gwynnda in July of 2021 is 1.63^{4}

## Problem 3

Import, clean, and tidy the dataset of baseline demographics:

``` r
MCI_baseline_df= read_csv("data/MCI_baseline.csv",skip = 1)|> 
  janitor::clean_names()|>   # can get the number of recruited participants
  mutate(
    sex=case_match(sex,
      1 ~ "male",
      0 ~ "female"
        ))|> 
  mutate(
    apoe4=case_match(apoe4,
      1 ~ "apoe4 carrier",
      0 ~ "apoe4 non-carrier"
        ))|>
  subset(!age_at_onset==".")|>   # can get the number of recruited participants that develop MCI
  #prepare for calculation the mean of age at onset
  mutate(age_at_onset=as.numeric(age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#Average baseline age

mean1=mean(MCI_baseline_df$age_at_onset)

#Proportion of women in the study are APOE4 carriers
number_female=count(MCI_baseline_df,sex==0)
number_apoe4_female=count(MCI_baseline_df,apoe4==1,sex==0)
# the number of female is 46; the number of female apoe4 carriers is 30.
prop=(number_apoe4_female$n[4]/number_female$n[2])*100
```

**Discussion:** First, we need to use `skip=1` to skip the first line of
csv file when we import the dataset since the first line of the csv file
is not the title of the variable that we want to show in the dataset. At
this stage, the baseline dataset has `483` observation of `6` variables
including patient id, sex, apoe4, age at onset and so on. In total,
`483` participants were recruited, `97` of them develop MCI. Average
baseline age is 70.26. From the dataset, NA% of women in the study are
APOE4 carriers.

Import, clean, and tidy the dataset of longitudinally observed biomarker
values:

``` r
MCI_amyloid_df= read_csv("data/mci_amyloid.csv",skip = 1)|> #import and skip the first line of dataset
  janitor::clean_names()|> #clean the name of variable
  rename(id=study_id) #rename the study_id variable to make it consistent with previous dataset
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Discussion:** The amyloid dataset has `487` observation and `6`
variables including id, the amyloid β 42/40 ratio at the baseline and at
the time2/4/6/8 of the study.

Combine the demographic and biomarker datasets:

``` r
MCI_df=
  left_join(MCI_baseline_df,MCI_amyloid_df, by="id")
```

**Discussion:** From the`MCI_df` dataset, we can find out that: there
are `3` participants only appears in the baseline experiment which means
they did not do any of the amyloid experiment at all. Also, many
participants miss one or two times of the amyloid experiment. The
resulting dataset has `97` observation and `11` variable including the
information from both datasets.

Save the combine dataset:

``` r
save(MCI_df,file="data/MCI_df.csv")
```
